In [ ]:
#Name:Sajag Agrawal
#Prn: 25070123100
#experiment-9
#Tools for EDA-Study of Numpy Library

In [ ]:
#declaration of Numpy

import numpy as np

a=np.array([1,5,9])
b=np.array([[1,2,3],[4,5,6]])
print("a=",a)
print("b=",b)
print()
#Dimension of array

print("dim of a:",a.ndim)
print("dim of b:",b.ndim)
print()
#shape of a and b determines no. of rows and column
print("shape of a:",a.shape)
print("shape of a:",b.shape)
print()
#datatype of a and b

print("datatype of a is:", a.dtype)
print("datatype of b is:",b.dtype)
print()
#In-Built funtions using Numpy

c=np.zeros((2,3)) #matrix of zero
print("matrix of zeroes:",c)
print()
d=np.ones((3,3)) #matrix of one
print("matrix of ones:",d)
print()

e=np.eye((3))
print("identity matrix",e)
print()

#arranging elements using numpy format=(start,end+1,increment)

f=np.arange(1,10,2)
print("arranged elements:",f)
print()

#linespace (gives elements in between the given elements format(start ,end ,no.of elemenets between them)) the step size is calculated by (end-start)/(no.of elemts-1)

g=np.linspace(0,1,4)
print("Linespace:",g)
print()

#sum and product using numpy

print("summed matrix a",a+5)
print()
print("multiplied matrix b\n",b*2)
print()

#calculating mean using numpy

h=np.mean(a)
print("mean of a:",h)
print()

#calculating median using numpy

i=np.median(a)
print("meadan of a:",i)
print()
#calculating max and min value

j=np.max(a)
print("max of a",j)
k=np.min(a)
print("min of a:",k)
print()

#sum of elements of a matriz using numpy

l=np.sum(a)
print("sum of elemnts of a:",l)
#transpose of matrix using numpy

m=np.transpose(b)
print("transpose of matrix a:\n",m)
print()




a= [1 5 9]
b= [[1 2 3]
 [4 5 6]]

dim of a: 1
dim of b: 2

shape of a: (3,)
shape of a: (2, 3)

datatype of a is: int64
datatype of b is: int64

matrix of zeroes: [[0. 0. 0.]
 [0. 0. 0.]]

matrix of ones: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

identity matrix [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arranged elements: [1 3 5 7 9]

Linespace: [0.         0.33333333 0.66666667 1.        ]

summed matrix a [ 6 10 14]

multiplied matrix b
 [[ 2  4  6]
 [ 8 10 12]]

mean of a: 5.0

meadan of a: 5.0

max of a 9
min of a: 1

sum of elemnts of a: 15
transpose of matrix a:
 [[1 4]
 [2 5]
 [3 6]]

